### ISSUE TITLE
Recover original request sent by custom application

### ISSUE THREAD

**Issue by itsmariohere** [lscorcia/keycloak-cieid-provider#1]
Hello, in a project I'm implementing your solution and it works correctly.
Due to some internal verification, I need to "forward" the ID of the original request and use it as ID of the request to CIE (and retrieve the SAML sent from CIE to Keycloak reading the field "InResponseTo").

Can i read in some way the SAML request to Keycloak in method "performLogin"? Other way is to read the RelayState, but as I can see is encoded differently from my project (maybe is not the same that I set from my application?).

Regards,

Mario

**Comment by lscorcia** [comment]
Hi! Currently Keycloak does not validate the InResponseTo attribute (see https://issues.redhat.com/browse/KEYCLOAK-17935). As this is a requirement for SPID, I already added this check to the SPID provider (https://github.com/italia/spid-keycloak-provider/commit/fac24f23d4f38e992cda6b6094a8bde6cd0861f3) and I will add it to the CIE provider as soon as possible.

As for reading the entire SAML request in the performLogin method, there is currently no way to access the entire request there. The supported approach is to add a client note with the required information to carry over instead.

**Comment by lscorcia** [comment]
Fixed in release [1.0.1](https://github.com/lscorcia/keycloak-cieid-provider/tree/1.0.1).
Thanks!
