### ISSUE TITLE
Keycloak 23 CIE ID Configuration

### ISSUE THREAD

**Issue by htsoft** [lscorcia/keycloak-cieid-provider#13]
Salve, sto provando a configurare il provider seguendo la wiki in keycloak 23.0.7

Ho creato il realm cied ed ho copiato il jar nella cartella /opt/keycloak/providers ed infatti CIE ID compare tra i provider. 
![image](https://github.com/lscorcia/keycloak-cieid-provider/assets/832779/a269087c-15d5-48c2-a168-cbc8ca4d8fb1)

ma quando clicco su CIE ID la schermata che mi compare è la seguente:
![image](https://github.com/lscorcia/keycloak-cieid-provider/assets/832779/cad4cec7-2fad-445c-b129-7aea054b23af)

Ed io non mi ritrovo con le istruzioni sulla WIKI, come posso proseguire?

Grazie,
Roberto

**Comment by nicolabeghin** [comment]
Ciao, fixato in https://github.com/nicolabeghin/keycloak-cieid-provider-configuration-client/commit/1b58847e55025da150a3f33fcd495fdc4accf599 - il client faceva riferimento al provider SPID che non essendo installato nella tua istanza faceva fallire l'import del metadata

**Comment by nicolabeghin** [comment]
Ciao fai riferimento al README in homepage https://github.com/lscorcia/keycloak-cieid-provider?tab=readme-ov-file#release-107-latest-keycloak-23xx-compatibility

> With the latest release targeting latest Keycloak 23.x.x it's not possible to configure the plugin through the Keycloak web UI, but only through REST services. Suggested to use https://github.com/nicolabeghin/keycloak-cieid-provider-configuration-client

**Comment by htsoft** [comment]
Ok, grazie mille
