### ISSUE TITLE
Errori di convalida del metadata

### ISSUE THREAD

**Issue by mspasiano** [lscorcia/keycloak-cieid-provider#3]
Nella validazione del metadata generato da keycloak riceviamo questo errore:
[/EntityDescriptor/Signature/KeyInfo/X509Data/X509Certificate] Elemento X509Certificate non presente

La URL del metadata è la seguente:
https://sso.cnr.it/auth/realms/CNR/cieid-sp-metadata

**Comment by mspasiano** [comment]
Arriva dalla procedura di validazione sul sito Federazione CIE, dal tool spid-sp-test locale non abbiamo riscontrato nessun problema.

**Comment by lscorcia** [comment]
Questo sembra in realtà un problema del validatore usato dal sito Federazione CIE, non c'è motivo per cui il tag X509Certificate debba essere embeddato nella signature del file XML (e infatti spid-sp-test non restituisce errore). Proverò a scrivere al supporto...

**Comment by krasholo** [comment]
Ciao, anche io ho riscontrato lo stesso problema, per caso hai ricevuto risposta dal supporto?

**Comment by mspasiano** [comment]
> Ciao, anche io ho riscontrato lo stesso problema, per caso hai ricevuto risposta dal supporto?

No, alla fine abbiamo deployato questo https://github.com/mspasiano/keycloak-cieid-provider/commit/7e73789e06a341669e55be047056f43ccd4abae3 e abbiamo passato la validazione

**Comment by krasholo** [comment]
Lo immaginavo, io ho fatto una prova aggiungendolo a mano nel metadata e quel passaggio l'ho superato. Per caso a te e' capitato di avere un errore "[/EntityDescriptor/Signature/KeyInfo/X509Data/X509Certificate] Certificato non valido"?

**Comment by mspasiano** [comment]
> Lo immaginavo, io ho fatto una prova aggiungendolo a mano nel metadata e quel passaggio l'ho superato. Per caso a te e' capitato di avere un errore "[/EntityDescriptor/Signature/KeyInfo/X509Data/X509Certificate] Certificato non valido"?

Non mi pare

**Comment by hello96** [comment]
Buongiorno @mspasiano @krasholo, anche io ho l'errore "[/EntityDescriptor/Signature/KeyInfo/X509Data/X509Certificate] Certificato non valido". Siete riusciti a capirci qualcosa?
Da quello che mi è parso di vedere, il certificato viene preso da quello della chiave RS256 del realm nel quale configuriamo il provider CIE, ma non ho ancora capito perchè non sia considerato non valido.

**Comment by ktsw89** [comment]
Salve a tutti, con la versione 26 di keycloak ho il medesimo errore:

- [/EntityDescriptor/Signature/KeyInfo/X509Data/X509Certificate] Certificato non valido 

Il messaggio arriva sempre dalla procedura di validazione sul sito Federazione CIE.

**Comment by nicolabeghin** [comment]
> Salve a tutti, con la versione 26 di keycloak ho il medesimo errore:
> 
> - [/EntityDescriptor/Signature/KeyInfo/X509Data/X509Certificate] Certificato non valido 
> 
> Il messaggio arriva sempre dalla procedura di validazione sul sito Federazione CIE.
> 
> 

Come hai configurato il plugin? Hai utilizzato https://github.com/nicolabeghin/keycloak-cieid-provider-configuration-client ?
Ti consiglio di verificare il certificato perché quelli usati per la validazione SPID (che poi dovrebbero essere i medesimo di CIE) sono scaduti e rinnovati da poco. Per il resto anche quest'ultima versione del plugin CIE é stata validata con i 100+ test di `spid-sp-test` profilo `cie` quindi escluderei regressioni importanti (oltre che é utilizzato in produzione) e propenderei per errori di configurazione dello stesso

**Comment by ktsw89** [comment]
Ho provato ad utilizzare il plugin ma senza successo, riporta un errore sull'importazione della configurazione dell'IdP.

```
Error deleting IdP cieid-production
Unable to find matching target resource method
Error deleting IdP cieid-testing
Unable to find matching target resource method
Error importing IdP configuration from metadata https://idserver.servizicie.interno.gov.it/idp/shibboleth?Metadata
Unable to find matching target resource method
/Users/ktsw/Downloads/keycloak-cieid-provider-configuration-client-master/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TypeError: Cannot read properties of undefined (reading 'data')
    at /Users/ktsw/Downloads/keycloak-cieid-provider-configuration-client-master/createidps.js:52:90
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by ktsw89** [comment]
Ho provato ad utilizzare il plugin ma ritorna Internal Server Error 500 in fase di importazione:

```
response:
   { status: 500,
     statusText: 'Internal Server Error',
     headers:
      { 'content-length': '94',
        connection: 'close',
        'content-type': 'application/json',
        'referrer-policy': 'no-referrer',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '1; mode=block' },
     config:
      { url:
         'http://localhost:22926/admin/realms/master/identity-provider/import-config',
        method: 'post',
        data:
         '{"providerId":"cieid-saml","fromUrl":"https://preproduzione.idserver.servizicie.interno.gov.it/idp/shibboleth?Metadata"}',
        headers: [Object],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        maxBodyLength: -1,
        httpsAgent: [Agent],
        validateStatus: [Function: validateStatus],
        transitional: [Object] },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'POST /admin/realms/master/identity-provider/import-config HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nAuthorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJUZXlqQnh6RXE4dG9ZeTJUNnU5cm5LaWF1cWx5clAtVW52RzZEcENNZS00In0.eyJleHAiOjE3NDU0MTE0MjcsImlhdCI6MTc0NTQxMTM2NywianRpIjoiYTIzZjY5MzctZGQ0YS00MDU3LWEzZDktNjgzNTIzYzQ1ZjgwIiwiaXNzIjoiaHR0cHM6Ly9zc28udHJlZWJlLml0L3JlYWxtcy9tYXN0ZXIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJzaWQiOiJiODc0MzhhMi04ODBiLTQ2YWYtOWIxNi03YTgwODNmZmQ1NTYiLCJzY29wZSI6InByb2ZpbGUgZW1haWwifQ.q6HnNzteMIVMh7Zhbu3GaiMkAVPE-wlF8Q6w1fKjuOSmFVIyb70JqHDVAud5LDk5d9l3llUsiqC52sqcAl-UYUQD9bKdPpttGF1cZlUSqEo2_dg4ksyFCAgxfpIbJpmgT6MLXk4cT_UMc4HBN7vFU4YYRdOnMA-FjDF3wzj8ssom_L3MeU7YRxqR4lBlxSiD3OUvae2KkKLeKPSPCH_Uc9J7ZetQGE_uDQfNhUQY8pvu5qQAB5r4mJh3Ie51MTnpFd2eaRQiBnPjTiPXWdoW4X2EpwRkTrtC2uoFI9NEa9URMyv3Bin2ec777_A_822OSH6B_3LAOaEHQXwHEt5IYQ\r\nUser-Agent: axios/0.21.4\r\nContent-Length: 120\r\nHost: localhost:22926\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        insecureHTTPParser: undefined,
        path: '/admin/realms/master/identity-provider/import-config',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data:
      { error: 'unknown_error',
        error_description: 'For more on this error consult the server log.' } },
  isAxiosError: true,
  toJSON: [Function: toJSON] }
```

Analizzando i log del server ad un certo punto trovo questo

`Uncaught server error: org.apache.http.conn.HttpHostConnectException: Connect to preproduzione.idserver.servizicie.interno.gov.it:443 [preproduzione.idserver.servizicie.interno.gov.it/2.42.225.154] failed: Connessione scaduta`

**Comment by nicolabeghin** [comment]
> Uncaught server error: org.apache.http.conn.HttpHostConnectException: Connect to preproduzione.idserver.servizicie.interno.gov.it:443

credo sia chiaro o sbaglio? :D Keycloak deve per forza di cose poter raggiungere l'host ufficiale del ministero dell'interno altrimenti non riesce per forza di cose a scaricare il metadata e importarlo.

**Comment by ktsw89** [comment]
No, purtroppo la cosa non è chiara. Non vedo come keycloak non possa raggiungere l'host del ministero. Inoltre, sopra ho già spid che funziona tranquillamente più altri identity providers. Per farlo funzionare con la versione 26 ho dovuto eliminare la stringa "/auth" da tutti gli url del plugin ed ho mantenuto nel file .env il link cieidTestingIdPMetadataURL = https://preproduzione.idserver.servizicie.interno.gov.it/idp/shibboleth?Metadata

**Comment by ktsw89** [comment]
Ad ogni modo ho scoperto il perché  dell'errore [/EntityDescriptor/Signature/KeyInfo/X509Data/X509Certificate] Elemento X509Certificate non presente: praticamente se si fa copia/incolla del metadata salta la digest/signature del xml. Per ovviare al problema ho fatto banalmente "tasto destro" -> "salva con nome" nella pagina del metadata et voilà, problema del certificato risolto. Praticamente il metadata non deve essere assolutamente modificato, anche un singolo spazio va a invalidare il tutto.

Ora però mi sono accorto che la federazione, per i soggetti privati vuole il tag 
<cie:Private xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions"/> anche in <md:ContactPerson contactType="technical"> mentre il metadata lo inserisce solo in <md:ContactPerson contactType="administrative">.

Praticamente la parte 

```
<md:ContactPerson contactType="administrative">
    <md:Extensions>
        <cie:Private xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions" />
        <cie:VATNumber xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">XXX</cie:VATNumber>
        <cie:FiscalCode xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">XXX</cie:FiscalCode>
        <cie:NACE2Code xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">J62</cie:NACE2Code>
        <cie:Municipality xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">072006</cie:Municipality>
        <cie:Province xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">BA</cie:Province>
        <cie:Country xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">IT</cie:Country>
    </md:Extensions>
    <md:Company>xxx</md:Company>
    <md:EmailAddress>info@xxx.it</md:EmailAddress>
    <md:TelephoneNumber>xxx</md:TelephoneNumber>
</md:ContactPerson>
<md:ContactPerson contactType="technical">
    <md:Extensions>
        <cie:VATNumber xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">XXX</cie:VATNumber>
        <cie:FiscalCode xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">XXX</cie:FiscalCode>
        <cie:NACE2Code xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">J62</cie:NACE2Code>
        <cie:Municipality xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">072006</cie:Municipality>
        <cie:Province xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">BA</cie:Province>
        <cie:Country xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">IT</cie:Country>
    </md:Extensions>
    <md:Company>xxx</md:Company>
    <md:EmailAddress>info@xxx.it</md:EmailAddress>
    <md:TelephoneNumber>+xxx</md:TelephoneNumber>
</md:ContactPerson>
```

deve diventare

```
<md:ContactPerson contactType="administrative">
    <md:Extensions>
        <cie:Private xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions" />
        <cie:VATNumber xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">XXX</cie:VATNumber>
        <cie:FiscalCode xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">XXX</cie:FiscalCode>
        <cie:NACE2Code xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">J62</cie:NACE2Code>
        <cie:Municipality xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">072006</cie:Municipality>
        <cie:Province xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">BA</cie:Province>
        <cie:Country xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">IT</cie:Country>
    </md:Extensions>
    <md:Company>xxx</md:Company>
    <md:EmailAddress>info@xxx.it</md:EmailAddress>
    <md:TelephoneNumber>xxx</md:TelephoneNumber>
</md:ContactPerson>
<md:ContactPerson contactType="technical">
    <md:Extensions>
        <cie:Private xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions" />
        <cie:VATNumber xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">XXX</cie:VATNumber>
        <cie:FiscalCode xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">XXX</cie:FiscalCode>
        <cie:NACE2Code xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">J62</cie:NACE2Code>
        <cie:Municipality xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">072006</cie:Municipality>
        <cie:Province xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">BA</cie:Province>
        <cie:Country xmlns:cie="https://www.cartaidentita.interno.gov.it/saml-extensions">IT</cie:Country>
    </md:Extensions>
    <md:Company>xxx</md:Company>
    <md:EmailAddress>info@xxx.it</md:EmailAddress>
    <md:TelephoneNumber>+xxx</md:TelephoneNumber>
</md:ContactPerson>
```
Ovviamente se si modifica il file a mano salta la digest/signature del xml rigenerando l'errore [/EntityDescriptor/Signature/KeyInfo/X509Data/X509Certificate] Elemento X509Certificate non presente

**Comment by ktsw89** [comment]
Ho aggiunto questo pezzo di codice nella classe CieIdSpMetadataResourceProvider

```
if (isSpPrivate)
{					
    // Private qualifier
    Element spTypeElement = doc.createElementNS(CIEID_METADATA_EXTENSIONS_NS, "cie:Private");
    spTypeElement.setAttributeNS(XMLNS_NS, "xmlns:cie", CIEID_METADATA_EXTENSIONS_NS);
    technicalContactPerson.getExtensions().addExtension(spTypeElement);
}
```
ricompilato ed aggiornato. Ora il metadata è corretto ed è stato preso senza alcun problema dal sito della federazione.

**Comment by nicolabeghin** [comment]
> Ho aggiunto questo pezzo di codice 

Se sottometti PR è ben accetta grazie!
