### ISSUE TITLE
keycloack 20

### ISSUE THREAD

**Issue by ac044** [lscorcia/keycloak-cieid-provider#5]
Ciao, è previsto l'aggiornamento alla versione 20 di keycloack per questo plugin?

**Comment by glatrofa** [comment]
Ciao, ho appena provato ad utilizzare questo plugin con `keycloak 20.0.0` e la validazione con `spid-sp-test v.1.2.13` funziona correttamente, dopo aver aggiunto queste righe di codice al file `CieIdSpMetadataResourceProvider.java` a riga 517:

```java
if (isSpPrivate)
{
    // Private qualifier
    Element spTypeElement = doc.createElementNS(CIEID_METADATA_EXTENSIONS_NS, "cie:Private");
    spTypeElement.setAttributeNS(XMLNS_NS, "xmlns:cie", CIEID_METADATA_EXTENSIONS_NS);
    technicalContactPerson.getExtensions().addExtension(spTypeElement);
}
else
{
    // Public qualifier
    Element spTypeElement = doc.createElementNS(CIEID_METADATA_EXTENSIONS_NS, "cie:Public");
    spTypeElement.setAttributeNS(XMLNS_NS, "xmlns:cie", CIEID_METADATA_EXTENSIONS_NS);
    technicalContactPerson.getExtensions().addExtension(spTypeElement);
}
```
 L'unica cosa che non funziona è l'invio della richiesta all'endpoint di test che ritorna l'errore "L'applicazione a cui hai acceduto non è registrata per l'utilizzo con questo servizio.". La richiesta non viene testata dal tool di validazione.

**Comment by nicolabeghin** [comment]
Closing as 24.x.x releases are available
