### ISSUE TITLE
Errori validazione metadata

### ISSUE THREAD

**Issue by Samuele-Z** [lscorcia/keycloak-cieid-provider#7]
Sto validando il metadata generato automaticamene da keycloak su demo.spid.gov.it.
Ottengo questi errori:
![immagine](https://user-images.githubusercontent.com/129092642/231975115-843f41d3-443b-487f-9d4d-b06587cb8804.png)
![immagine](https://user-images.githubusercontent.com/129092642/231975367-b2610b82-5f5f-44c6-9e8b-4e070d666d96.png)
![immagine](https://user-images.githubusercontent.com/129092642/231975548-c4761e22-655d-4e68-a13d-3a46d8f9f837.png)
Sto usando questa istanza di keycloak per avere autenticazione sia SPID che CIE.
Keycloak 19.0.3
La validazione del metadata per SPID è andata a buon fine.
Tutti i campi del plugin provider CIE sono compilati.

Come posso risolvere?
Grazie

**Comment by nicolabeghin** [comment]
Chiudo, trattasi di repository per CIEID non SPID
