### ISSUE TITLE
Campo "Import from URL" mancante

### ISSUE THREAD

**Issue by hello96** [lscorcia/keycloak-cieid-provider#8]
Ciao,
ho installato keycloak wildfly versione 19.0.3 e ho seguito tutte le indicazioni della pagina wiki "Installing the CIE ID provider". 
Nella pagina "Defining the CIE ID IdP" si fa riferimento al campo Import from URL, nel quale andrebbe inserito l'url del metadata in base all'ambiente scelto, però nell'interfaccia di keycloak, nella sezione "Add provider" vedo solo questo:

![image](https://user-images.githubusercontent.com/31999705/235979400-e6dc3395-0a0d-4cd3-8896-d734a11792c7.png)

Sto sbagliando qualcosa?

Grazie in anticipo per la risposta :)

**Comment by hello96** [comment]
Ciao,
purtroppo devo riaprire la issue perchè mi è stato stata richiesta una versione del provider per keycloak 19.0.3.
Con la 16.1.1, come da tue indicazioni, funzionava tutto 👍

Ho letto anche la wiki riguardo keycloak spid provider, e lì è espressamente detto che per utilizzare il plugin con versioni di keycloak 19.x non è possibile utilizzare l'Admin Console Theme v2, ma solo quello precedente.

Il cliente per cui devo rilasciare il provider, però, è già abituato alla versione nuova del tema ed ha già altri plugin in uso, quindi devo inventarmi qualcosa 😆

Pensi che posso adattare il tuo progetto al mio caso d'uso? Sai darmi qualche consiglio a riguardo? 

Ti ringrazio in anticipo!

**Comment by nicolabeghin** [comment]
Risolto con ultima versione del plugin per Keycloak 24 con cui è stato possibile tornare ad ereditare le funzionalità OOTB SAML di Keycloak per IdP custom come questo
