### ISSUE TITLE
Indicazioni per configurare il flusso di autenticazione

### ISSUE THREAD

**Issue by hello96** [lscorcia/keycloak-cieid-provider#9]
Buongiorno,
ho seguito la wiki (scritta benissimo 👍) fino alla pagina "Configuring the Authentication Flow" senza problemi, e vedo che questa sezione è per adesso vuota.

Posso chiedervi qualche indicazione per configurare il flusso di autenticazione? Nel frattempo darò uno sguardo anche al codice, in ogni caso se potete darmi qualche hint in merito ve ne sono molto grata🙏

**Comment by lscorcia** [comment]
Ciao,
puoi seguire le indicazioni analoghe per il provider SPID su https://github.com/italia/spid-keycloak-provider/wiki/Configuring-the-Authentication-Flow .
